Feature/icky:736-builder-plugin
KiboSoftware/builder pull request #1
Opened 2022-09-28 15:25 UTC by kibo-sushant

2022-09-28 22:13 UTC, kibo-kevinwatts requested changes

2022-09-28 22:13 UTC, kibo-kevinwatts commented on plugins/kibo-commerce/src/plugin.jsx
> +            filter: searchTerm ? `categoryCode eq ${searchTerm}`: ""
filter: `content.name cont ${searchTerm} or categoryCode eq ${searchTerm}`

2022-09-28 22:13 UTC, kibo-kevinwatts commented on plugins/kibo-commerce/src/plugin.jsx
> +          let products = await kiboClient.perfromProductSearch(searchOptions);
fix typo, `performProductSearch`

2022-09-28 22:13 UTC, kibo-kevinwatts commented on plugins/kibo-commerce/src/plugin.jsx
> +          const products = await kiboClient.getItemsByProductCode(PAGE_SIZE, [productCode]);
why pass a PAGE_SIZE here, since we're doing it by product code?

2022-09-28 22:13 UTC, kibo-kevinwatts commented on plugins/kibo-commerce/src/plugin.jsx
> +      handle: resource?.categoryCode,
Map handle to resource?.content?.slug

2022-09-28 22:13 UTC, kibo-kevinwatts commented on plugins/kibo-commerce/src/plugin.jsx
> +
Add a `async findByHandle(handle: string)` method here that performs a lookup by category slug
```
async findByHandle(handle: string) {
     let searchOptions = {
         filter: `content.slug eq ${handle}`
     }
      let categories =  await kiboClient.performCategorySearch(searchOptions)
}
```

2022-09-29 06:35 UTC, kibo-sushant commented on plugins/kibo-commerce/src/plugin.jsx
> +            filter: searchTerm ? `categoryCode eq ${searchTerm}`: ""
resolved

2022-09-29 06:36 UTC, kibo-sushant commented on plugins/kibo-commerce/src/plugin.jsx
> +          let products = await kiboClient.perfromProductSearch(searchOptions);
resolved

2022-09-29 06:36 UTC, kibo-sushant commented on plugins/kibo-commerce/src/plugin.jsx
> +          const products = await kiboClient.getItemsByProductCode(PAGE_SIZE, [productCode]);
resolved. also removed PAGE_SIZE from category => findById

2022-09-29 06:36 UTC, kibo-sushant commented on plugins/kibo-commerce/src/plugin.jsx
> +      handle: resource?.categoryCode,
resolved

2022-09-29 06:37 UTC, kibo-sushant commented on plugins/kibo-commerce/src/plugin.jsx
> +
resolved

2022-09-30 01:41 UTC, merged